name: d3f_shared
version: 1.0.0+1
publish_to: none
description: d3f_shared.
environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  d3f_dependency_manager:
    git:
      url: https://github.com/DanhDue-ExOICTIF/d3f_dependency_manager.git
      ref: develop

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.10+1
  build_runner: ^2.2.1
  json_serializable: ^6.4.1
  hive_generator: ^1.1.3
  freezed: ^2.1.0+1
  flutter_gen_runner: ^5.0.1
  theme_tailor: ^1.0.6
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: true
  assets:
    outputs:
      class_name: SharedAssets
      style: dot-delimiter
      package_parameter_enabled: true
    enabled: true
  colors:
    outputs:
      class_name: D3FColors
      style: dot-delimiter
      package_parameter_enabled: false
    inputs:
      - assets/colors/colors.xml
    enable: true
  fonts:
    outputs:
      class_name: D3FFontFamily
    enabled: true
  line_length: 80

flutter:
  module:
    androidPackage: com.danhdue.d3f_shared
    iosBundleIdentifier: com.danhdue.d3fShared
    androidX: true
  assets:
    - assets/images/
    - assets/lotties/
    - assets/jsons/
  fonts:
    - family: SfCompactRegular
      fonts:
        - asset: assets/fonts/SF_Compact_Display_Regular.ttf
    - family: SfCompactMedium
      fonts:
        - asset: assets/fonts/SF_Compact_Display_Medium.ttf
    - family: SfCompactSemiBold
      fonts:
        - asset: assets/fonts/SF_Compact_Display_Semibold.ttf
    - family: SfCompactBold
      fonts:
        - asset: assets/fonts/SF_Compact_Display_Bold.ttf
  uses-material-design: true
